### ISSUE TITLE
Aides à ajouter

### ISSUE THREAD

**Issue by mquandalle** [betagouv/publicodes-aides-velo#16]
- [x] https://www.binic-etables-sur-mer.fr/actualites/une-aide-financiere-pour-lachat-dun-velo-ou-broyeur-de-vegetaux-ou-recuperateur-deau-de-pluie/
- [ ] Ville de Lannion https://www.lannion.bzh/velo-achat-aide-lannion (cumulable avec Lannion-Trégor Communauté)
- [x] https://www.creusot-montceau.org/actualite/la-communaute-urbaine-vous-aide-financierement-pour-lacquisition-dun-velo/
- [x] https://www.lorient-agglo.bzh/services/deplacements/aide-achat-velo/ (désactivé dans la base de règles, je ne sais pas pourquoi)
- [x] Territoire de l'Ouest https://www.tco.re/wp-content/uploads/2024/09/formulaire-aide-acquisition-vae.pdf
- [x] https://7vallees.fr/la-communaute-de-communes-des-7-vallees-peut-vous-aider-a-acheter-un-velo/
- [x] https://www.mairievilliersenbiere.fr/aide-a-lacquisition-de-velos/
- [x] https://www.arc-sud-bretagne.fr/wp-content/uploads/2024/09/2024_07_11_REGLEMENT_PRIME-ACHAT-VAE_CARGO.pdf
- [ ] https://villeneuvelezavignon.com/formulaires-en-ligne/subvention-vae-et-pieges-a-moustiques/ (cumulable avec grand avignon)
- [ ] https://www.soleval.org/vos-besoins/une-entreprise/analyses-d-opportunite-etudes-prospectives-aides-financieres.html
- [x] https://www.pevelecarembault.fr/actualites/des-le-4-mars-demandez-votre-prime-velo-electrique
- [x] https://www.lesportesbriardes.fr/2023/12/28/beneficiez-dune-aide-a-lachat-de-velo/
- [x] Arc Sud Bretagne https://www.arc-sud-bretagne.fr/au-quotidien/mobilite/
- [ ] https://www.royat.fr/actualites/la-ville-de-royat-aide-les-royaderes-pour-lachat-de-velos-electriques/
- [x] https://www.paysdessorgues.fr/aide-financiere-achat-velo
- [x] https://valparisis.fr/aide-achat-velo
- [x] https://mobilite.dlva.fr/aide-a-lacquisition-velo-a-assistance-electrique/

**Comment by EmileRolley** [comment]
Aides manquantes partagées par Mes Aides France Travail :

- [ ] https://www.charenton.fr/velo/velo_pass-velo/
- [ ] https://www.vaucresson.fr/mon-cadre-de-vie/mobilite/velos-electriques/
- [ ] https://paysdelor.fr/vivre-ici/transports/velo/
- [ ] https://www.saintmartindecrau.fr/-Prime-a-l-achat-d-un-velo-.html
- [ ] https://www.arras.fr/fr/me-deplacer/circulation/donner-une-vraie-place-au-velo-arras
- [ ] https://planvelo.bassinpompey.fr/primevelo
- [ ] https://www.st2b.fr/fileo/prime-a-lacquisition-dun-velo-a-assistance-electrique/
- [ ] https://ccov.fr/communaute-de-communes/vie-quotidienne/mobilite/subvention-vae
- [ ] https://www.cc-terredeau.fr/fr/velos-electriques.html
- [ ] https://www.ccphva.com/VAE
- [ ] https://www.ccce.fr/aide-achat-vae/

**Comment by mquandalle** [comment]
Le bonus vélo de l'état est supprimé depuis le 2 décembre https://www.economie.gouv.fr/cedef/bonus-ecologique-velo-electrique
